cluster.name: xmq_es
node.name: master
node.master: true
node.data: false
index.refresh_interval: 5s
network.host: 0.0.0.0
network.publish_host: 172.21.0.3
transport.tcp.port: 9300
http.port: 9200
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: 172.21.0.2:9300