cluster.name: xmq_es
node.name: node1
node.master: false
node.data: true
index.refresh_interval: 5s
network.host: 0.0.0.0
network.publish_host: 172.21.0.5
transport.tcp.port: 9300
http.port: 9200
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: 172.21.0.2:9300